name: nexus_ar
description: "Proyecto de TEDS"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2
  mapbox_maps_flutter: ^2.12.0
  geolocator: ^10.0.0
  image: ^4.0.17
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  mobile_scanner: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true